# Generated by Django 4.1.3 on 2022-11-28 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_alter_comment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='likes',
            field=models.ManyToManyField(related_name='challenge_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
